# Site wide configuration

<<<<<<< HEAD
title:            Ryan P. Randall
locale:           en_US
url:              # http://ryan-p-randall.github.io
=======
title:            Site Title
locale:           en_US
url:              http://localhost:4000
>>>>>>> 3ba1427cca2854b431210b483a312e77a1d00704


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
<<<<<<< HEAD
  name: Ryan P. Randall
  avatar: bio-photo.jpg
  bio: "Critical information literacy ∴ Literary, cultural & media studies scholar ∴ MLS student at IU-Bloomington ∴ Sous les pavés, la plage ∴ We are, as always, stubborn, stoked, and petrified - GY!BE"
  email: 
  disqus-shortname: 
  twitter: foureyedsoul
  facebook: #username
  google:
    plus: #username
    analytics: UA-49717180-1
=======
  name: Your Name
  avatar: bio-photo.jpg
  bio: "Describe your self."
  email: 
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
>>>>>>> 3ba1427cca2854b431210b483a312e77a1d00704
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
<<<<<<< HEAD
  github: ryan-p-randall
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: foureyedsoul
  tumblr: not-evenly-distributed
=======
  github: #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
>>>>>>> 3ba1427cca2854b431210b483a312e77a1d00704
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
