# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"
title: "Ryan P. Randall"
title_separator: "—"
subtitle:
name: "Ryan P. Randall"
email:
description: >- # this means to ignore newlines until "baseurl:"
  "Ryan P. Randall's website, Ph.D. student, and community college librarian blog"
url: "http://ryanpatrickrandall.com"
baseurl: ""
repository: "ryan-p-randall/ryan-p-randall.github.io"
lifespan: 2014-2020
teaser:  
logo:  
masthead_title: 
og_image: /assets/images/pocket-notebooks-square.jpg
breadcrumbs: true  
words_per_minute: 160  
comments:  
  provider: false # "utterances"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
twitter_username: foureyedsoul
github_username: ryan-p-randall
minimal_mistakes_skin: dark-citrus-sage
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Boise # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ryan P. Randall"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Instruction Coordinator & Faculty Outreach Librarian at the College of Western Idaho ∴ Literary, media, & cultural studies ∴ Web Editor at _In the Library with the Lead Pipe_. ∴ Another world is possible."
  location: "Boise, Idaho"
# uri: http://www.ryanpatrickrandall.com
  twitter: foureyedsoul
  github: ryan-p-randall
# links:
  #  - label: "Website"
  #    icon: "fas fa-fw fa-link"
  #    url: "https://www.ryanpatrickrandall.com/mm-github-pages-starter"
  #  - label: "Twitter"
  #    icon: "fab fa-fw fa-twitter-square"
  #    url: "https://twitter.com/foureyedsoul"
  #  - label: "GitHub"
  #    icon: "fab fa-fw fa-github"
  #    url: "https://github.com/ryan-p-randall"
  #  - label: "Instagram"
  #    icon: "fab fa-fw fa-instagram"
  #    url: "https://instagram.com/"

footer:
  # links:
  #  - label: "Twitter"
  #    icon: "fab fa-fw fa-twitter-square"
  #    url: "https://twitter.com/"
  #  - label: "GitHub"
  #    icon: "fab fa-fw fa-github"
  #    url: "https://github.com/"
  #  - label: "Instagram"
  #    icon: "fab fa-fw fa-instagram"
  #    url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# scripts
