# Site wide configuration

title: Ryan P. Randall ∴ Info Fluxus
locale: en_US
url: http://ryan-p-randall.github.io
baseurl: http://www.ryanpatrickrandall.com
repository: "ryan-p-randall/ryan-p-randall.github.io"
timezone: America/Boise
lifespan: 2014–2019

# Jekyll configuration

permalink: /:year/:title/
markdown: kramdown
syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll/scholar
  - jekyll-gist
  - rouge

kramdown:
  auto_ids: true
  input: GFM
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
     default_lang: html

# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Site owner
owner:
  name: Ryan P. Randall
  avatar: bio-photo.jpg
  bio: "Instruction Coordinator & Faculty Outreach Librarian at the College of Western Idaho ∴ Literary, media & cultural studies ∴ Web Editor at In the Library with the Lead Pipe ∴ Sous les pavés, la plage ∴ We are, as always, stubborn, stoked, and petrified - GY!BE"
  email:
  disqus-shortname:
  mastodon: foureyedsoul
  twitter: foureyedsoul
  facebook: #username
  google:
    plus: #username
    analytics: #UA-49717180-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ryan-p-randall
  leadpipe: about/editorial/board/ryan-randall/
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: foureyedsoul
  lastfm: foureyedsoul
  tumblr: foureyedsoul
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  goodreads: 2077359-ryan
  soundcloud: foureyedsoul
  zotero: ryanprandall
  academia: ryanrandall
  youtube: #username
  weibo: #username
  flickr: #username
  codepen: #username

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true


comments:
  provider               : "staticman" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master" # "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "LICENSE", "README.md"]
